### ISSUE TITLE
/var/lib/isso should be owned by isso user

### ISSUE THREAD

**Issue by hobgoblinsmaster** [jgraichen/debian-isso#8]
Just created and installed the package and can't start isso:
Traceback (most recent call last):
  File "/usr/bin/isso", line 9, in <module>
    load_entry_point('isso==0.9.10', 'console_scripts', 'isso')()
  File "/usr/lib/python2.7/dist-packages/isso/__init__.py", line 262, in main
    run_simple(host, port, make_app(conf), threaded=True,
  File "/usr/lib/python2.7/dist-packages/isso/__init__.py", line 168, in make_app
    isso = App(conf)
  File "/usr/lib/python2.7/dist-packages/isso/__init__.py", line 91, in __init__
    self.db = db.SQLite3(conf.get('general', 'dbpath'), conf)
  File "/usr/lib/python2.7/dist-packages/isso/db/__init__.py", line 35, in __init__
    "SELECT name FROM sqlite_master"
  File "/usr/lib/python2.7/dist-packages/isso/db/__init__.py", line 61, in execute
    with sqlite3.connect(self.path) as con:
sqlite3.OperationalError: unable to open database file

If I run chown isso /var/lib/isso/, it then can start without error

**Comment by JocelynDelalande** [comment]
@hobgoblinsmaster Thanks for reporting, and sorry for delay.

Can you actually reproduce it on a fresh install ? after install, permissions are those for me : 

$ ls -l /var/lib/ |grep isso
drwxr-xr-x  2 isso          root           4096 sept. 12 21:19 isso

Which is fine.

**Comment by JocelynDelalande** [comment]
@hobgoblinsmaster could you confirm it works ? (I updated http://packages.crapouillou.net with fixed version)
